spring:
  application:
    name: Hotel Astolfo
  ## DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/?useSSL=false
    username: enihsyou
    password: enihsyou
    sql-script-encoding: utf-8
    initialize: true
    # Schema (DDL) script resource references.
    schema: classpath:hotel_schema.sql
    # Data (DML) script resource references.
    data: classpath:hotel_data.sql
    name: astolfo_hotel
    # Hikari先不使用
    # hikari:
    #   connection-init-sql: "SET NAMES 'utf8mb4'"

  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
  session:
    store-type: hash_map

#  mail:
#    host:
#    port:
#    username:
#    password:
#    protocol:
#    jndi-name:
#    test-connection: true

## EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  address: localhost
  port: 80
  connection-timeout: 2000

  compression:
    enabled: true
  tomcat:
    uri-encoding: utf-8

banner:
  location: banner.txt
  image:
    location: banner.jpg
    width: 80
    margin: 0
mybatis:
  type-aliases-package: com.enihsyou.astolfo.hotel.domain
#  mapper-locations: com.enihsyou.astolfo.hotel.mybatis.mapper.xml
#  config-location: mybatis.xml
  configuration:
#    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3
    default-executor-type: BATCH
logging:
  level:
    com.enihsyou.astolfo.hotel.mybatis:
      mapper: TRACE
security:
  basic:
    enabled: false


#---
#
#spring:
#    profiles: development
#server:
#    port: 8080
#
#---
#
#spring:
#    profiles: production
#server:
#    port: 0
