spring:
  application:
    name: Hotel Astolfo
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/astolfo_hotel?useSSL=false
    username: enihsyou
    password: enihsyou
    schema: classpath*:hotel_schema.sql
    data: classpath*:hotel_data.sql
#    initialize: true
  jpa:
    show-sql: true
  session:
    store-type: hash_map
  jackson:
    serialization:
      write_dates_as_timestamps: false
  h2:
    console:
      enabled: true
      settings:
        trace: true
server:
  address: localhost
  port: 80
  connection-timeout: 2000
  compression:
    enabled: true
  tomcat:
    uri-encoding: utf-8
banner:
  image:
    width: 80
    margin: 0
security:
  basic:
    enabled: true
    path: /api/**
    realm: Astolfo
  enable-csrf: false
  user:
    name: test
    password: 2333
  ignored: /api/users/login, /api/users/signup

